
package ua.nure.sherbakov.practice7.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Flowers", targetNamespace = "http://practice7.sherbakov.nure.ua/server/service", wsdlLocation = "http://localhost:9090/flowers?wsdl")
public class Flowers
    extends Service
{

    private final static URL FLOWERS_WSDL_LOCATION;
    private final static WebServiceException FLOWERS_EXCEPTION;
    private final static QName FLOWERS_QNAME = new QName("http://practice7.sherbakov.nure.ua/server/service", "Flowers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/flowers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLOWERS_WSDL_LOCATION = url;
        FLOWERS_EXCEPTION = e;
    }

    public Flowers() {
        super(__getWsdlLocation(), FLOWERS_QNAME);
    }

    public Flowers(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLOWERS_QNAME, features);
    }

    public Flowers(URL wsdlLocation) {
        super(wsdlLocation, FLOWERS_QNAME);
    }

    public Flowers(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLOWERS_QNAME, features);
    }

    public Flowers(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Flowers(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlowerService
     */
    @WebEndpoint(name = "FlowerPort")
    public FlowerService getFlowerPort() {
        return super.getPort(new QName("http://practice7.sherbakov.nure.ua/server/service", "FlowerPort"), FlowerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlowerService
     */
    @WebEndpoint(name = "FlowerPort")
    public FlowerService getFlowerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://practice7.sherbakov.nure.ua/server/service", "FlowerPort"), FlowerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLOWERS_EXCEPTION!= null) {
            throw FLOWERS_EXCEPTION;
        }
        return FLOWERS_WSDL_LOCATION;
    }

}
