//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.07 at 12:10:04 PM CET 
//

package ua.nure.sherbakov.practice7.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Multipling.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Multipling"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="leaves"/&gt;
 *     &lt;enumeration value="feces"/&gt;
 *     &lt;enumeration value="seeds"/&gt;
 *     &lt;pattern value="leaves|feces|seeds"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Multipling")
@XmlEnum
public enum Multipling {

	@XmlEnumValue("leaves")
	LEAVES("leaves"),
	@XmlEnumValue("feces")
	FECES("feces"),
	@XmlEnumValue("seeds")
	SEEDS("seeds");

	private final String value;

	Multipling(String v) {
		value = v.toLowerCase();
	}

	public String value() {
		return value.toLowerCase();
	}

	public static Multipling fromValue(String v) {
		for (Multipling c : Multipling.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
