//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.14 at 01:38:45 PM CEST 
//

package ua.nure.sherbakov.practice7.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Flower complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Flower"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Soil" type="{http://sherbakov.nure.ua/practice7/entity}Soil"/&gt;
 *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="VisualParameters" type="{http://sherbakov.nure.ua/practice7/entity}VisualParameters"/&gt;
 *         &lt;element name="GrovingTips" type="{http://sherbakov.nure.ua/practice7/entity}GrovingTips"/&gt;
 *         &lt;element name="Multipling" type="{http://sherbakov.nure.ua/practice7/entity}Multipling"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Flower", propOrder = { "name", "soil", "origin", "visualParameters", "grovingTips", "multipling" })
public class Flower {

	@XmlElement(name = "Name", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String name;
	@XmlElement(name = "Soil", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String soil;
	@XmlElement(name = "Origin", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String origin;
	@XmlElement(name = "VisualParameters", required = true)
	protected VisualParameters visualParameters;
	@XmlElement(name = "GrovingTips", required = true)
	protected GrovingTips grovingTips;
	@XmlElement(name = "Multipling", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String multipling;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the soil property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoil() {
		return soil;
	}

	/**
	 * Sets the value of the soil property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setSoil(String value) {
		this.soil = value;
	}

	/**
	 * Gets the value of the origin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * Sets the value of the origin property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOrigin(String value) {
		this.origin = value;
	}

	/**
	 * Gets the value of the visualParameters property.
	 * 
	 * @return possible object is {@link VisualParameters }
	 * 
	 */
	public VisualParameters getVisualParameters() {
		return visualParameters;
	}

	/**
	 * Sets the value of the visualParameters property.
	 * 
	 * @param value allowed object is {@link VisualParameters }
	 * 
	 */
	public void setVisualParameters(VisualParameters value) {
		this.visualParameters = value;
	}

	/**
	 * Gets the value of the grovingTips property.
	 * 
	 * @return possible object is {@link GrovingTips }
	 * 
	 */
	public GrovingTips getGrovingTips() {
		return grovingTips;
	}

	/**
	 * Sets the value of the grovingTips property.
	 * 
	 * @param value allowed object is {@link GrovingTips }
	 * 
	 */
	public void setGrovingTips(GrovingTips value) {
		this.grovingTips = value;
	}

	/**
	 * Gets the value of the multipling property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMultipling() {
		return multipling;
	}

	/**
	 * Sets the value of the multipling property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMultipling(String value) {
		this.multipling = value;
	}

	@Override
	public String toString() {
		return new StringBuilder().append("Name = ").append(getName()).append("\n").append("Soil = ").append(getSoil())
				.append("\n").append("Origin = ").append(getOrigin()).append("\n").append(getVisualParameters())
				.append("\n").append(getGrovingTips()).append("\n").append("Multipling = ").append(getMultipling())
				.append("\n").toString();
	}

}
